# Generated by Django 3.0.5 on 2020-04-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainCalendar', '0001_initial'),
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ManyToManyField(to='MainCalendar.Course'),
        ),
    ]
