app_id: "d7445665-43de-4990-a09a-215ca2e6706a"
app_secret: "nuhzoYUFI0935_*trHHX3#@"
redirect: "http://localhost:8000/callback"
scopes: "openid profile offline_access user.read calendars.readwrite"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"
