# Generated by Django 3.0.5 on 2020-04-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
