# Generated by Django 3.0.5 on 2020-08-26 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainCalendar', '0002_auto_20200817_1007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.SmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='timetabletemplate',
            name='cycle',
        ),
        migrations.CreateModel(
            name='WeekTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('cells', models.ManyToManyField(to='MainCalendar.Cell')),
            ],
        ),
        migrations.AddField(
            model_name='timetabletemplate',
            name='weeks',
            field=models.ManyToManyField(to='MainCalendar.WeekTemplate'),
        ),
    ]
