# Generated by Django 3.0.5 on 2020-08-26 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainCalendar', '0003_auto_20200826_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetabletemplate',
            old_name='timeInterval',
            new_name='interval',
        ),
    ]
