# Generated by Django 3.0.5 on 2020-08-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_student_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='course',
        ),
    ]
